# Apply method for Series

In [4]:
import pandas as pd
import numpy as np
from IPython.display import display

students=pd.Series(data=[120,130,150,200,100],index=['A','B','C',
'D','E'])
display(students)
print(type(students))

A    120
B    130
C    150
D    200
E    100
dtype: int64

<class 'pandas.core.series.Series'>

In [5]:
def cm_to_feet(h):
    return np.round(h/30.48 ,2)
print(students.apply(cm_to_feet))

A    3.94
B    4.27
C    4.92
D    6.56
E    3.28
dtype: float64

# Apply method for DataFrame

In [10]:
data1=pd.DataFrame({'EmployeeName': ['Callen Dunkley', 'Sarah Rayner', 'Jeanette Sloan', 'Kaycee Acosta', 'Henri Conroy', 'Emma Peralta', 'Martin Butt', 'Alex Jensen', 'Kim Howarth', 'Jane Burnett'],
                    'Department': ['Accounting', 'Engineering', 'Engineering', 'HR', 'HR', 'HR', 'Data Science', 'Data Science', 'Accounting', 'Data Science'],
                    'HireDate': [2010, 2018, 2012, 2014, 2014, 2018, 2020, 2018, 2020, 2012],
                    'Sex': ['M', 'F', 'F', 'F', 'M', 'F', 'M', 'M', 'M', 'F'],
                    'Birthdate': ['04/09/1982', '14/04/1981', '06/05/1997', '08/01/1986', '10/10/1988', '12/11/1992', '10/04/1991', '16/07/1995', '08/10/1992', '11/10/1979'],
                    'Weight': [78, 80, 66, 67, 90, 57, 115, 87, 95, 57],
                    'Height': [176, 160, 169, 157, 185, 164, 195, 180, 174, 165],
                    'Kids': [2, 1, 0, 1, 1, 0, 2, 0, 3, 1]
                    })

display(data1)

,EmployeeName,Department,HireDate,Sex,Birthdate,Weight,Height,Kids
0,Callen Dunkley,Accounting,2010,M,04/09/1982,78,176,2
1,Sarah Rayner,Engineering,2018,F,14/04/1981,80,160,1
2,Jeanette Sloan,Engineering,2012,F,06/05/1997,66,169,0
3,Kaycee Acosta,HR,2014,F,08/01/1986,67,157,1
4,Henri Conroy,HR,2014,M,10/10/1988,90,185,1
5,Emma Peralta,HR,2018,F,12/11/1992,57,164,0
6,Martin Butt,Data Science,2020,M,10/04/1991,115,195,2
7,Alex Jensen,Data Science,2018,M,16/07/1995,87,180,0
8,Kim Howarth,Accounting,2020,M,08/10/1992,95,174,3
9,Jane Burnett,Data Science,2012,F,11/10/1979,57,165,1

In [11]:
data1['FirstName']=data1['EmployeeName'].apply(lambda x: x.split()[0])
data1["LastName"]=data1["EmployeeName"].apply(lambda x : x.split()[1])
display(data1)

,EmployeeName,Department,HireDate,Sex,Birthdate,Weight,Height,Kids,FirstName,LastName
0,Callen Dunkley,Accounting,2010,M,04/09/1982,78,176,2,Callen,Dunkley
1,Sarah Rayner,Engineering,2018,F,14/04/1981,80,160,1,Sarah,Rayner
2,Jeanette Sloan,Engineering,2012,F,06/05/1997,66,169,0,Jeanette,Sloan
3,Kaycee Acosta,HR,2014,F,08/01/1986,67,157,1,Kaycee,Acosta
4,Henri Conroy,HR,2014,M,10/10/1988,90,185,1,Henri,Conroy
5,Emma Peralta,HR,2018,F,12/11/1992,57,164,0,Emma,Peralta
6,Martin Butt,Data Science,2020,M,10/04/1991,115,195,2,Martin,Butt
7,Alex Jensen,Data Science,2018,M,16/07/1995,87,180,0,Alex,Jensen
8,Kim Howarth,Accounting,2020,M,08/10/1992,95,174,3,Kim,Howarth
9,Jane Burnett,Data Science,2012,F,11/10/1979,57,165,1,Jane,Burnett

In [12]:
import pandas as pd

airline_series = pd.Series(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet', 'Vistara'])
duration_series = pd.Series(['2h 5m', '2h', '50m', '1h 30m', '3h 20m'])
arrival_time_series = pd.Series(['21:45', '10:00', '00:50', '15:30', '19:15'])
departure_time_series = pd.Series(['19:40', '07:55', '00:44', '14:00', '15:55'])
distance_series = pd.Series([2050, 2000, 220, 800, 3000])

df=pd.DataFrame({
    'Airline': airline_series,
    'Duration': duration_series,
    'Arrival Time': arrival_time_series,
    'Departure Time': departure_time_series,
    'Distance (km)': distance_series
})

data=pd.DataFrame(df)
data

       Airline Duration Arrival Time Departure Time  Distance (km)
0       IndiGo    2h 5m        21:45          19:40           2050
1    Air India       2h        10:00          07:55           2000
2  Jet Airways      50m        00:50          00:44            220
3     SpiceJet   1h 30m        15:30          14:00            800
4      Vistara   3h 20m        19:15          15:55           3000

In [13]:
def min_sec(s):
    sec=0
    a=s.split()
    for i in range(len(a)):
        if "h" in a[i]:
            sec +=int(a[i][:-1])*60*60
        if "m" in a[i]:
            sec +=int(a[i][:-1])*60
    return sec

In [14]:
data["new_duration"]=data["Duration"].apply(min_sec)
data

,Airline,Duration,Arrival Time,Departure Time,Distance (km),new_duration
0,IndiGo,2h 5m,21:45,19:40,2050,7500
1,Air India,2h,10:00,07:55,2000,7200
2,Jet Airways,50m,00:50,00:44,220,3000
3,SpiceJet,1h 30m,15:30,14:00,800,5400
4,Vistara,3h 20m,19:15,15:55,3000,12000

In [18]:
def hr(time):
    time=time.split(':')
    hour=int(time[0])
    if 5<=hour and hour<12:
        return "Morning"
    if 12<=hour and hour<17:
        return "Afternoon"
    if 17<=hour and hour<=20:
        return "evening"
    if 20<=hour and hour<=24:
        return "Night"

In [19]:
data['Arrival Time'] = data["Arrival Time"].apply(hr)

In [20]:
data

,Airline,Duration,Arrival Time,Departure Time,Distance (km),new_duration
0,IndiGo,2h 5m,Night,19:40,2050,7500
1,Air India,2h,Morning,07:55,2000,7200
2,Jet Airways,50m,None,00:44,220,3000
3,SpiceJet,1h 30m,Afternoon,14:00,800,5400
4,Vistara,3h 20m,evening,15:55,3000,12000

# Mapping values using a dictionary

In [25]:
data_map={
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40]
}

df_map=pd.DataFrame(data_map)

mapping={"Alice":'A','Bob' : 'B','Charlie':'C','David':'D'}
df_map['Mapped Name']=df_map['Name'].map(mapping)
df_map

      Name  Age Mapped Name
0    Alice   25           A
1      Bob   30           B
2  Charlie   35           C
3    David   40           D

# Mapping values using a function

In [26]:
def map_age(age):
    if age<30:
        return "Young"
    elif age>=30 and age <40:
        return "Middle-aged"
    else:
        return 'Senior'

df_map['Age Group']=df_map['Age'].map(map_age)

df_map

      Name  Age Mapped Name    Age Group
0    Alice   25           A        Young
1      Bob   30           B  Middle-aged
2  Charlie   35           C  Middle-aged
3    David   40           D       Senior