In [11]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame(
    {
        "col1": ["a", "a", "b", "b", "a"],
        "col2": [1.0, 2.0, 3.0, np.nan, 5.0],
        "col3": [1.0, 2.0, 3.0, 4.0, 5.0],
    },
    columns=["col1", "col2", "col3"],
)

df1

  col1  col2  col3
0    a   1.0   1.0
1    a   2.0   2.0
2    b   3.0   3.0
3    b   NaN   4.0
4    a   5.0   5.0

In [12]:
df2=df1.copy()
df2

  col1  col2  col3
0    a   1.0   1.0
1    a   2.0   2.0
2    b   3.0   3.0
3    b   NaN   4.0
4    a   5.0   5.0

In [13]:
print(df1.compare(df2))

Empty DataFrame
Columns: []
Index: []

In [14]:
df2

  col1  col2  col3
0    a   1.0   1.0
1    a   2.0   2.0
2    b   3.0   3.0
3    b   NaN   4.0
4    a   5.0   5.0

In [16]:
df2.loc[0,"col1"]="c"
df2.loc[2,'col3']=4.0
df2

  col1  col2  col3
0    c   1.0   1.0
1    a   2.0   2.0
2    b   3.0   4.0
3    b   NaN   4.0
4    a   5.0   5.0

In [17]:
df1.compare(df2)

  col1       col3
  self other self other
0    a     c  NaN   NaN
2  NaN   NaN  3.0   4.0

In [18]:
df1.compare(df2,align_axis=0)

        col1  col3
0 self     a   NaN
  other    c   NaN
2 self   NaN   3.0
  other  NaN   4.0

In [20]:
df3=df1.copy()
df3.loc[0,'col1']='c'
df3.loc[1,'col2']=100
df3.loc[2,'col3']=4.0
df3

  col1   col2  col3
0    c    1.0   1.0
1    a  100.0   2.0
2    b    3.0   4.0
3    b    NaN   4.0
4    a    5.0   5.0

In [21]:
df1.compare(df3)

  col1       col2        col3
  self other self  other self other
0    a     c  NaN    NaN  NaN   NaN
1  NaN   NaN  2.0  100.0  NaN   NaN
2  NaN   NaN  NaN    NaN  3.0   4.0

In [22]:
df1['col2'].equals(df3['col2'])

False

In [25]:
output=pd.Series(df1['col2'] ==df2['col2'])
output

0     True
1     True
2     True
3    False
4     True
Name: col2, dtype: bool

In [26]:
df1.loc[output]

  col1  col2  col3
0    a   1.0   1.0
1    a   2.0   2.0
2    b   3.0   3.0
4    a   5.0   5.0