# Concat in pandas

In [1]:
import pandas as pd

In [2]:
temp_data=pd.DataFrame({
    'Date': ['12-02-2023', '13-02-2023', '14-02-2023', '15-02-2023', '16-02-2023'],
    'TempMax': [24.3, 26.9, 23.4, 15.5, 16.1 ]
})

rainfall_data=pd.DataFrame({
    'Date': ['12-02-2023', '13-02-2023', '14-02-2023', '15-02-2023', '16-02-2023'],
    'Rainfall': [0, 3.6, 3.6, 39.8, 2.8 ]})

In [3]:
result_col=pd.concat([temp_data,rainfall_data])
print("\nConcatenate along rows:")
print(result_col)

Concatenate along rows:
         Date  TempMax  Rainfall
0  12-02-2023     24.3       NaN
1  13-02-2023     26.9       NaN
2  14-02-2023     23.4       NaN
3  15-02-2023     15.5       NaN
4  16-02-2023     16.1       NaN
0  12-02-2023      NaN       0.0
1  13-02-2023      NaN       3.6
2  14-02-2023      NaN       3.6
3  15-02-2023      NaN      39.8
4  16-02-2023      NaN       2.8

In [4]:
result_col=pd.concat([temp_data,rainfall_data],axis=1)
print("\nConcatenate along columns:")
print(result_col)

Concatenate along columns:
         Date  TempMax        Date  Rainfall
0  12-02-2023     24.3  12-02-2023       0.0
1  13-02-2023     26.9  13-02-2023       3.6
2  14-02-2023     23.4  14-02-2023       3.6
3  15-02-2023     15.5  15-02-2023      39.8
4  16-02-2023     16.1  16-02-2023       2.8

# ignoring index

In [5]:
result_col_false_ignore=pd.concat([temp_data,rainfall_data],axis=0,ignore_index=False)
print("\n Concatenate along columns with ignore_index = False:")
print(result_col_false_ignore)

result_col_true_ignore=pd.concat([temp_data,rainfall_data],axis=0,ignore_index=True)
print("\n Concatenate along columns with ignore_index=True")
print(result_col_true_ignore)

 Concatenate along columns with ignore_index = False:
         Date  TempMax  Rainfall
0  12-02-2023     24.3       NaN
1  13-02-2023     26.9       NaN
2  14-02-2023     23.4       NaN
3  15-02-2023     15.5       NaN
4  16-02-2023     16.1       NaN
0  12-02-2023      NaN       0.0
1  13-02-2023      NaN       3.6
2  14-02-2023      NaN       3.6
3  15-02-2023      NaN      39.8
4  16-02-2023      NaN       2.8

 Concatenate along columns with ignore_index=True
         Date  TempMax  Rainfall
0  12-02-2023     24.3       NaN
1  13-02-2023     26.9       NaN
2  14-02-2023     23.4       NaN
3  15-02-2023     15.5       NaN
4  16-02-2023     16.1       NaN
5  12-02-2023      NaN       0.0
6  13-02-2023      NaN       3.6
7  14-02-2023      NaN       3.6
8  15-02-2023      NaN      39.8
9  16-02-2023      NaN       2.8

# join

In [6]:
result_col_inner=pd.concat([temp_data,rainfall_data],axis=0,join='inner')
print("\n Concatenate with inner join:")
print(result_col_inner)

result_col_outer=pd.concat([temp_data,rainfall_data],axis=0,join='outer')
print('\n Concatenate with outer join:')
print(result_col_outer)

 Concatenate with inner join:
         Date
0  12-02-2023
1  13-02-2023
2  14-02-2023
3  15-02-2023
4  16-02-2023
0  12-02-2023
1  13-02-2023
2  14-02-2023
3  15-02-2023
4  16-02-2023

 Concatenate with outer join:
         Date  TempMax  Rainfall
0  12-02-2023     24.3       NaN
1  13-02-2023     26.9       NaN
2  14-02-2023     23.4       NaN
3  15-02-2023     15.5       NaN
4  16-02-2023     16.1       NaN
0  12-02-2023      NaN       0.0
1  13-02-2023      NaN       3.6
2  14-02-2023      NaN       3.6
3  15-02-2023      NaN      39.8
4  16-02-2023      NaN       2.8

In [16]:
data1={
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Score': [85, 90, 88] 
}

df1= pd.DataFrame(data1)

data2={
    'Name': ['David', 'Eve', 'Charlie'],
    'Age': [27, 32, 35],
    'Score': [82, 88, 88],
    "extra":[100,100,100]
}
df2=pd.DataFrame(data2)

print("DataFrame 1:\n", df1)
print("\nDataFrame 2:\n",df2)

DataFrame 1:
       Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     88

DataFrame 2:
       Name  Age  Score  extra
0    David   27     82    100
1      Eve   32     88    100
2  Charlie   35     88    100

In [8]:
result_col_inner2=pd.concat([df1,df2],axis=0,join='inner',ignore_index=True)
result_col_inner2

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     88
3    David   27     82
4      Eve   32     88
5  Charlie   35     88

In [9]:
result_col_inner2_1=pd.concat([df1,df2],axis=1,ignore_index=True)
result_col_inner2_1

         0   1   2        3   4   5    6
0    Alice  25  85    David  27  82  100
1      Bob  30  90      Eve  32  88  100
2  Charlie  35  88  Charlie  35  88  100

# keys

In [10]:
result_col_key1=pd.concat([df1,df2],axis=0 ,keys=('A','B'))
print("\n Concatenate along columns with keys, axis=0:")
print(result_col_key1)

 Concatenate along columns with keys, axis=0:
        Name  Age  Score  extra
A 0    Alice   25     85    NaN
  1      Bob   30     90    NaN
  2  Charlie   35     88    NaN
B 0    David   27     82  100.0
  1      Eve   32     88  100.0
  2  Charlie   35     88  100.0

In [11]:
result_col_key2=pd.concat([df1,df2],axis=1,keys=('A','B'))
print("\n Concatenate along columns with keys, axis=1: ")
print(result_col_key2)

 Concatenate along columns with keys, axis=1:
         A                  B
      Name Age Score     Name Age Score extra
0    Alice  25    85    David  27    82   100
1      Bob  30    90      Eve  32    88   100
2  Charlie  35    88  Charlie  35    88   100

In [12]:
result_col_key1.loc["A"]

      Name  Age  Score  extra
0    Alice   25     85    NaN
1      Bob   30     90    NaN
2  Charlie   35     88    NaN

In [13]:
result_col_key1.loc['A']["Score"]

0    85
1    90
2    88
Name: Score, dtype: int64

In [14]:
result_col_key1.loc['A']["Score"][0]

np.int64(85)

In [15]:
result_col_key2=pd.concat([temp_data,rainfall_data],axis=1,keys='AB')
print('\n Cincatenate along with keys ,axis=1:')
print(result_col_key2)

 Cincatenate along with keys ,axis=1:
            A                   B
         Date TempMax        Date Rainfall
0  12-02-2023    24.3  12-02-2023      0.0
1  13-02-2023    26.9  13-02-2023      3.6
2  14-02-2023    23.4  14-02-2023      3.6
3  15-02-2023    15.5  15-02-2023     39.8
4  16-02-2023    16.1  16-02-2023      2.8