# Data Manipulation

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
np.random.seed(42)
dates = pd.date_range('2023-01-01', '2023-03-31')
products = ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard']
regions = ['North', 'South', 'East', 'West']

sales_data = pd.DataFrame({
    'Date': np.random.choice(dates, 500),
    'Product': np.random.choice(products, 500),
    'Region': np.random.choice(regions, 500),
    'Units_Sold': np.random.randint(1, 20, 500),
    'Unit_Price': np.random.uniform(100, 2000, 500).round(2),
    'Customer_ID': np.random.randint(1000, 1100, 500)
})
sales_data['Total_Sales'] = sales_data['Units_Sold'] * sales_data['Unit_Price']

In [3]:
sales_data

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
...,...,...,...,...,...,...,...
495,2023-02-09,Keyboard,South,10,444.51,1032,4445.10
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78

In [4]:
sales_data.head()

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60

In [5]:
sales_data.describe()

                      Date  Units_Sold   Unit_Price  Customer_ID   Total_Sales
count                  500  500.000000   500.000000   500.000000    500.000000
mean   2023-02-13 07:26:24   10.054000  1038.592700  1049.500000  10346.006300
min    2023-01-01 00:00:00    1.000000   100.630000  1000.000000    124.160000
25%    2023-01-22 00:00:00    5.000000   562.865000  1024.000000   3608.475000
50%    2023-02-13 12:00:00   10.000000  1057.750000  1049.000000   8299.140000
75%    2023-03-05 00:00:00   15.000000  1513.830000  1073.000000  15261.470000
max    2023-03-31 00:00:00   19.000000  1991.410000  1099.000000  34340.580000
std                    NaN    5.393446   536.397786    28.644214   8101.725382

In [6]:
sales_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         500 non-null    datetime64[us]
 1   Product      500 non-null    str
 2   Region       500 non-null    str
 3   Units_Sold   500 non-null    int32
 4   Unit_Price   500 non-null    float64
 5   Customer_ID  500 non-null    int32
 6   Total_Sales  500 non-null    float64
dtypes: datetime64[us](1), float64(2), int32(2), str(2)
memory usage: 23.6 KB

In [7]:
sales_data.isnull().sum().sort_values(ascending=False)

Date           0
Product        0
Region         0
Units_Sold     0
Unit_Price     0
Customer_ID    0
Total_Sales    0
dtype: int64

In [8]:
sales_data.shape

(500, 7)

Q1. Select all sales from the 'North' region

In [12]:
sales_data[sales_data['Region']=="North"]

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
5,2023-03-24,Phone,North,10,1111.27,1003,11112.70
...,...,...,...,...,...,...,...
489,2023-02-20,Tablet,North,5,361.86,1020,1809.30
490,2023-02-12,Tablet,North,1,1359.78,1068,1359.78
492,2023-03-08,Tablet,North,19,438.91,1019,8339.29
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78


Q2. Select sales of 'Laptop' or 'Phone' with more than 10 units sold

In [15]:
sales_data[(sales_data.Product.isin(['Laptop','Phone'])) & (sales_data.Units_Sold >10)]

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
8,2023-03-16,Phone,North,17,372.73,1029,6336.41
10,2023-01-24,Phone,West,14,1492.51,1018,20895.14
11,2023-01-03,Phone,South,15,408.53,1030,6127.95
15,2023-03-29,Laptop,East,16,545.67,1048,8730.72
17,2023-02-07,Phone,North,18,585.08,1082,10531.44
...,...,...,...,...,...,...,...
475,2023-01-04,Laptop,North,12,1682.09,1085,20185.08
477,2023-01-24,Phone,South,15,1524.14,1054,22862.10
479,2023-01-02,Phone,East,12,1388.92,1092,16667.04
493,2023-03-06,Phone,South,14,155.24,1066,2173.36
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44

Q3. Select columns 'Product', 'Region', and 'Total_Sales' for all records

In [21]:
sales_data.loc[:,["Product","Region","Total_Sales"]]

      Product Region  Total_Sales
0    Keyboard  North     23386.68
1     Monitor  South     18033.15
2       Phone  North      5247.27
3    Keyboard  North     14186.77
4      Tablet  North     11265.60
..        ...    ...          ...
495  Keyboard  South      4445.10
496    Laptop   West     15058.44
497   Monitor  North      9508.62
498    Tablet  South      3522.20
499   Monitor  North     19245.78

[500 rows x 3 columns]

In [16]:
sales_data

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
...,...,...,...,...,...,...,...
495,2023-02-09,Keyboard,South,10,444.51,1032,4445.10
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78