# Data Manipulation

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
np.random.seed(42)
dates = pd.date_range('2023-01-01', '2023-03-31')
products = ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard']
regions = ['North', 'South', 'East', 'West']

sales_data = pd.DataFrame({
    'Date': np.random.choice(dates, 500),
    'Product': np.random.choice(products, 500),
    'Region': np.random.choice(regions, 500),
    'Units_Sold': np.random.randint(1, 20, 500),
    'Unit_Price': np.random.uniform(100, 2000, 500).round(2),
    'Customer_ID': np.random.randint(1000, 1100, 500)
})
sales_data['Total_Sales'] = sales_data['Units_Sold'] * sales_data['Unit_Price']

In [4]:
sales_data

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
...,...,...,...,...,...,...,...
495,2023-02-09,Keyboard,South,10,444.51,1032,4445.10
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78

In [5]:
sales_data.head()

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60

In [6]:
sales_data.describe()

                      Date  Units_Sold   Unit_Price  Customer_ID   Total_Sales
count                  500  500.000000   500.000000   500.000000    500.000000
mean   2023-02-13 07:26:24   10.054000  1038.592700  1049.500000  10346.006300
min    2023-01-01 00:00:00    1.000000   100.630000  1000.000000    124.160000
25%    2023-01-22 00:00:00    5.000000   562.865000  1024.000000   3608.475000
50%    2023-02-13 12:00:00   10.000000  1057.750000  1049.000000   8299.140000
75%    2023-03-05 00:00:00   15.000000  1513.830000  1073.000000  15261.470000
max    2023-03-31 00:00:00   19.000000  1991.410000  1099.000000  34340.580000
std                    NaN    5.393446   536.397786    28.644214   8101.725382

In [7]:
sales_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         500 non-null    datetime64[us]
 1   Product      500 non-null    str
 2   Region       500 non-null    str
 3   Units_Sold   500 non-null    int32
 4   Unit_Price   500 non-null    float64
 5   Customer_ID  500 non-null    int32
 6   Total_Sales  500 non-null    float64
dtypes: datetime64[us](1), float64(2), int32(2), str(2)
memory usage: 23.6 KB

In [8]:
sales_data.isnull().sum().sort_values(ascending=False)

Date           0
Product        0
Region         0
Units_Sold     0
Unit_Price     0
Customer_ID    0
Total_Sales    0
dtype: int64

In [9]:
sales_data.shape

(500, 7)

Q1. Select all sales from the 'North' region

In [10]:
sales_data[sales_data['Region']=="North"]

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
5,2023-03-24,Phone,North,10,1111.27,1003,11112.70
...,...,...,...,...,...,...,...
489,2023-02-20,Tablet,North,5,361.86,1020,1809.30
490,2023-02-12,Tablet,North,1,1359.78,1068,1359.78
492,2023-03-08,Tablet,North,19,438.91,1019,8339.29
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78


Q2. Select sales of 'Laptop' or 'Phone' with more than 10 units sold

In [11]:
sales_data[(sales_data.Product.isin(['Laptop','Phone'])) & (sales_data.Units_Sold >10)]

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
8,2023-03-16,Phone,North,17,372.73,1029,6336.41
10,2023-01-24,Phone,West,14,1492.51,1018,20895.14
11,2023-01-03,Phone,South,15,408.53,1030,6127.95
15,2023-03-29,Laptop,East,16,545.67,1048,8730.72
17,2023-02-07,Phone,North,18,585.08,1082,10531.44
...,...,...,...,...,...,...,...
475,2023-01-04,Laptop,North,12,1682.09,1085,20185.08
477,2023-01-24,Phone,South,15,1524.14,1054,22862.10
479,2023-01-02,Phone,East,12,1388.92,1092,16667.04
493,2023-03-06,Phone,South,14,155.24,1066,2173.36
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44

Q3. Select columns 'Product', 'Region', and 'Total_Sales' for all records

In [12]:
sales_data.loc[:,["Product","Region","Total_Sales"]]

      Product Region  Total_Sales
0    Keyboard  North     23386.68
1     Monitor  South     18033.15
2       Phone  North      5247.27
3    Keyboard  North     14186.77
4      Tablet  North     11265.60
..        ...    ...          ...
495  Keyboard  South      4445.10
496    Laptop   West     15058.44
497   Monitor  North      9508.62
498    Tablet  South      3522.20
499   Monitor  North     19245.78

[500 rows x 3 columns]

In [13]:
sales_data

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15
2,2023-03-13,Phone,North,9,583.03,1079,5247.27
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60
...,...,...,...,...,...,...,...
495,2023-02-09,Keyboard,South,10,444.51,1032,4445.10
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78

## Grouping Operations: ##

Q4 Calculate the average units sold by region

In [14]:
sales_data.groupby('Region')['Units_Sold'].mean()

Region
East      9.875000
North    10.395522
South     9.968504
West      9.945946
Name: Units_Sold, dtype: float64

Q5. Find the top 3 customers by total spending

In [15]:
data_sales=sales_data.groupby('Customer_ID')['Total_Sales'].sum()
data_sales.sort_values(ascending=False).head(3)

Customer_ID
1047    127658.62
1013    124894.36
1063    121376.18
Name: Total_Sales, dtype: float64

In [16]:
data_sales.nlargest(3)

Customer_ID
1047    127658.62
1013    124894.36
1063    121376.18
Name: Total_Sales, dtype: float64

Q6. Find the total sales by product

In [17]:
sales_data.groupby('Product')['Total_Sales'].sum()

Product
Keyboard    1074551.96
Laptop      1199835.35
Monitor      950987.34
Phone        959547.49
Tablet       988081.01
Name: Total_Sales, dtype: float64

` Filtering:`

Q7. Find all sales above $5000

In [18]:
sales_data["Unit_Price"] > 5000

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: Unit_Price, Length: 500, dtype: bool

Q8. Find the most expensive single sale for each product

In [19]:
sales_data.groupby("Product")["Total_Sales"].max()

Product
Keyboard    34340.58
Laptop      31371.30
Monitor     31343.41
Phone       33616.98
Tablet      33548.40
Name: Total_Sales, dtype: float64

Q9. Find all sales that occurred on weekends

In [20]:
day_no=sales_data['Date'].dt.dayofweek
day_no=day_no > 4
day_no

0      False
1       True
2      False
3      False
4       True
       ...
495    False
496    False
497     True
498    False
499     True
Name: Date, Length: 500, dtype: bool

In [21]:
def price_cat(u_price):
    if u_price<300:
        return "Budget"
    elif u_price >=300 and u_price <1000:
        return "Mid-Range0"
    else:
        return "Premium"

sales_data['Price_Category']=sales_data.Unit_Price.apply(price_cat)
sales_data

,Date,Product,Region,Units_Sold,Unit_Price,Customer_ID,Total_Sales,Price_Category
0,2023-02-21,Keyboard,North,12,1948.89,1002,23386.68,Premium
1,2023-01-15,Monitor,South,15,1202.21,1087,18033.15,Premium
2,2023-03-13,Phone,North,9,583.03,1079,5247.27,Mid-Range0
3,2023-03-02,Keyboard,North,13,1091.29,1057,14186.77,Premium
4,2023-01-21,Tablet,North,15,751.04,1054,11265.60,Mid-Range0
...,...,...,...,...,...,...,...,...
495,2023-02-09,Keyboard,South,10,444.51,1032,4445.10,Mid-Range0
496,2023-03-15,Laptop,West,18,836.58,1072,15058.44,Mid-Range0
497,2023-02-12,Monitor,North,11,864.42,1060,9508.62,Mid-Range0
498,2023-02-13,Tablet,South,2,1761.10,1008,3522.20,Premium
499,2023-01-29,Monitor,North,18,1069.21,1067,19245.78,Premium

Exercise 2: Employee Data Analysis

In [22]:
import pandas as pd 
import numpy as np

In [23]:
# Create sample employee data
np.random.seed(42)
departments = ['Engineering', 'Marketing', 'Finance', 'HR', 'Sales']
positions = ['Junior', 'Mid', 'Senior', 'Manager', 'Director']

employee_data = pd.DataFrame({
    'Employee_ID': range(1001, 1051),
    'Name': [f'Employee_{i}' for i in range(1, 51)],
    'Department': np.random.choice(departments, 50),
    'Position': np.random.choice(positions, 50),
    'Salary': np.random.randint(40000, 150000, 50),
    'Join_Date': pd.to_datetime(np.random.choice(pd.date_range('2018-01-01', '2023-01-01'), 50)),
    'Performance_Score': np.random.randint(1, 101, 50)
})

In [24]:
employee_data

,Employee_ID,Name,Department,Position,Salary,Join_Date,Performance_Score
0,1001,Employee_1,HR,Manager,92251,2019-07-11,3
1,1002,Employee_2,Sales,Manager,62662,2022-05-17,56
2,1003,Employee_3,Finance,Manager,48392,2020-10-09,81
3,1004,Employee_4,Sales,Director,70535,2019-10-08,59
4,1005,Employee_5,Sales,Senior,118603,2020-03-06,2
5,1006,Employee_6,Marketing,Junior,92256,2020-11-17,2
6,1007,Employee_7,Finance,Manager,129135,2022-07-02,92
7,1008,Employee_8,Finance,Mid,75222,2022-04-29,54
8,1009,Employee_9,Finance,Manager,117373,2021-09-25,87
9,1010,Employee_10,Sales,Mid,119575,2022-12-27,96
10,1011,Employee_11,HR,Mid,136354,2021-09-16,97
11,1012,Employee_12,Finance,Manager,124651,2022-07-22,1
12,1013,Employee_13,Sales,Director,103335,2022-03-10,19
13,1014,Employee_14,Marketing,Mid,50965,2021-10-03,2
14,1015,Employee_15,HR,Mid,64538,2022-02-05,53
15,1016,Employee_16,Marketing,Manager,148066,2021-06-08,44
16,1017,Employee_17,HR,Mid,110592,2018-07-09,90
17,1018,Employee_18,Sales,Mid,138018,2021-06-02,32
18,1019,Employee_19,Engineering,Manager,48110,2021-11-09,70
19,1020,Employee_20,HR,Manager,119309,2021-11-01,32
20,1021,Employee_21,Marketing,Junior,67266,2021-07-30,68
21,1022,Employee_22,Sales,Director,92992,2019-09-25,55
22,1023,Employee_23,HR,Director,122948,2019-09-20,75
23,1024,Employee_24,Engineering,Mid,138806,2020-08-30,56
24,1025,Employee_25,Engineering,Director,46910,2022-11-04,17
25,1026,Employee_26,Finance,Mid,130982,2021-07-06,38
26,1027,Employee_27,Finance,Junior,40206,2021-10-14,24
27,1028,Employee_28,Marketing,Manager,127054,2019-12-11,69
28,1029,Employee_29,HR,Manager,127897,2022-01-19,98
29,1030,Employee_30,HR,Manager,63419,2021-12-05,70
30,1031,Employee_31,Finance,Director,90636,2019-10-11,86
31,1032,Employee_32,HR,Junior,90015,2018-11-14,11
32,1033,Employee_33,HR,Director,147059,2022-08-28,16
33,1034,Employee_34,Engineering,Director,94268,2021-06-02,97
34,1035,Employee_35,Finance,Junior,127939,2021-06-11,73
35,1036,Employee_36,Sales,Junior,58141,2019-11-15,59
36,1037,Employee_37,Finance,Junior,120356,2019-10-26,70
37,1038,Employee_38,Sales,Junior,145878,2021-10-29,80
38,1039,Employee_39,Engineering,Manager,111910,2022-08-23,93
39,1040,Employee_40,Marketing,Senior,96044,2022-06-20,3
40,1041,Employee_41,HR,Senior,107214,2022-02-04,20
41,1042,Employee_42,Engineering,Junior,73827,2021-06-10,59
42,1043,Employee_43,HR,Senior,95820,2022-09-12,36
43,1044,Employee_44,Marketing,Senior,102623,2021-02-10,19
44,1045,Employee_45,Marketing,Junior,121734,2022-03-01,90
45,1046,Employee_46,Engineering,Senior,115450,2019-03-18,67
46,1047,Employee_47,Marketing,Director,133426,2019-07-18,19
47,1048,Employee_48,Sales,Mid,62299,2021-07-15,20
48,1049,Employee_49,Marketing,Mid,83585,2022-03-14,96
49,1050,Employee_50,HR,Junior,149225,2021-11-10,71

### Tasks:

1. **Basic Operations**:
   - Find all employees in Engineering with salary > $80,000
   - Count the number of employees in each department
   - Find the average salary by position level

2. **Time-Based Analysis**:
   - Calculate employee tenure in years. Suppose the end date is `'2023-01-01'`
   - Find employees who joined in 2020
   - Calculate the average performance score by year of joining

3. **Advanced Grouping**:
   - For each department, find the highest and lowest salary
   - Find departments where the average performance score is above 70

4. **Apply and Transform**:
   - Apply a 5% salary increase to all employees with performance score > 80

In [33]:
employee_data[(employee_data["Department"]=="Engineering")  & (employee_data["Salary"]>80000)]

,Employee_ID,Name,Department,Position,Salary,Join_Date,Performance_Score
23,1024,Employee_24,Engineering,Mid,138806,2020-08-30,56
33,1034,Employee_34,Engineering,Director,94268,2021-06-02,97
38,1039,Employee_39,Engineering,Manager,111910,2022-08-23,93
45,1046,Employee_46,Engineering,Senior,115450,2019-03-18,67

In [35]:
employee_data["Department"].value_counts()

Department
HR             13
Sales          10
Finance        10
Marketing      10
Engineering     7
Name: count, dtype: int64

In [37]:
# avg salary  by position level
employee_data.groupby("Position")["Salary"].mean()

Position
Director    100234.333333
Junior       98803.909091
Manager     101556.076923
Mid         100994.181818
Senior      105959.000000
Name: Salary, dtype: float64

2. **Time-Based Analysis**:
   - Calculate employee tenure in years. Suppose the end date is `'2023-01-01'`
   - Find employees who joined in 2020
   - Calculate the average performance score by year of joining

In [41]:
end_date=pd.to_datetime('2023-01-01')
employee_data["Tenure_Years"]=((end_date - employee_data["Join_Date"]).dt.days/365.25).round(2)

3. **Advanced Grouping**:
   - For each department, find the highest and lowest salary
   - Find departments where the average performance score is above 70

4. **Apply and Transform**:
   - Apply a 5% salary increase to all employees with performance score > 80

In [44]:
employee_data.groupby("Department")['Salary'].agg(["max","min"])

                max    min
Department
Engineering  138806  46910
Finance      130982  40206
HR           149225  63419
Marketing    148066  50965
Sales        145878  58141

In [47]:
avg_perf_dept=employee_data.groupby("Department")["Performance_Score"].mean()
high_perf_dept=avg_perf_dept[avg_perf_dept>70]

In [48]:
employee_data['Adjusted_Salary'] = employee_data.apply(
    lambda row: row['Salary'] * 1.05 if row['Performance_Score'] > 80 else row['Salary'],
    axis=1
)

In [42]:
employee_data

,Employee_ID,Name,Department,Position,Salary,Join_Date,Performance_Score,Tenure_Years
0,1001,Employee_1,HR,Manager,92251,2019-07-11,3,3.48
1,1002,Employee_2,Sales,Manager,62662,2022-05-17,56,0.63
2,1003,Employee_3,Finance,Manager,48392,2020-10-09,81,2.23
3,1004,Employee_4,Sales,Director,70535,2019-10-08,59,3.23
4,1005,Employee_5,Sales,Senior,118603,2020-03-06,2,2.82
5,1006,Employee_6,Marketing,Junior,92256,2020-11-17,2,2.12
6,1007,Employee_7,Finance,Manager,129135,2022-07-02,92,0.50
7,1008,Employee_8,Finance,Mid,75222,2022-04-29,54,0.68
8,1009,Employee_9,Finance,Manager,117373,2021-09-25,87,1.27
9,1010,Employee_10,Sales,Mid,119575,2022-12-27,96,0.01
10,1011,Employee_11,HR,Mid,136354,2021-09-16,97,1.29
11,1012,Employee_12,Finance,Manager,124651,2022-07-22,1,0.45
12,1013,Employee_13,Sales,Director,103335,2022-03-10,19,0.81
13,1014,Employee_14,Marketing,Mid,50965,2021-10-03,2,1.25
14,1015,Employee_15,HR,Mid,64538,2022-02-05,53,0.90
15,1016,Employee_16,Marketing,Manager,148066,2021-06-08,44,1.57
16,1017,Employee_17,HR,Mid,110592,2018-07-09,90,4.48
17,1018,Employee_18,Sales,Mid,138018,2021-06-02,32,1.58
18,1019,Employee_19,Engineering,Manager,48110,2021-11-09,70,1.14
19,1020,Employee_20,HR,Manager,119309,2021-11-01,32,1.17
20,1021,Employee_21,Marketing,Junior,67266,2021-07-30,68,1.42
21,1022,Employee_22,Sales,Director,92992,2019-09-25,55,3.27
22,1023,Employee_23,HR,Director,122948,2019-09-20,75,3.28
23,1024,Employee_24,Engineering,Mid,138806,2020-08-30,56,2.34
24,1025,Employee_25,Engineering,Director,46910,2022-11-04,17,0.16
25,1026,Employee_26,Finance,Mid,130982,2021-07-06,38,1.49
26,1027,Employee_27,Finance,Junior,40206,2021-10-14,24,1.22
27,1028,Employee_28,Marketing,Manager,127054,2019-12-11,69,3.06
28,1029,Employee_29,HR,Manager,127897,2022-01-19,98,0.95
29,1030,Employee_30,HR,Manager,63419,2021-12-05,70,1.07
30,1031,Employee_31,Finance,Director,90636,2019-10-11,86,3.23
31,1032,Employee_32,HR,Junior,90015,2018-11-14,11,4.13
32,1033,Employee_33,HR,Director,147059,2022-08-28,16,0.34
33,1034,Employee_34,Engineering,Director,94268,2021-06-02,97,1.58
34,1035,Employee_35,Finance,Junior,127939,2021-06-11,73,1.56
35,1036,Employee_36,Sales,Junior,58141,2019-11-15,59,3.13
36,1037,Employee_37,Finance,Junior,120356,2019-10-26,70,3.18
37,1038,Employee_38,Sales,Junior,145878,2021-10-29,80,1.17
38,1039,Employee_39,Engineering,Manager,111910,2022-08-23,93,0.36
39,1040,Employee_40,Marketing,Senior,96044,2022-06-20,3,0.53
40,1041,Employee_41,HR,Senior,107214,2022-02-04,20,0.91
41,1042,Employee_42,Engineering,Junior,73827,2021-06-10,59,1.56
42,1043,Employee_43,HR,Senior,95820,2022-09-12,36,0.30
43,1044,Employee_44,Marketing,Senior,102623,2021-02-10,19,1.89
44,1045,Employee_45,Marketing,Junior,121734,2022-03-01,90,0.84
45,1046,Employee_46,Engineering,Senior,115450,2019-03-18,67,3.79
46,1047,Employee_47,Marketing,Director,133426,2019-07-18,19,3.46
47,1048,Employee_48,Sales,Mid,62299,2021-07-15,20,1.46
48,1049,Employee_49,Marketing,Mid,83585,2022-03-14,96,0.80
49,1050,Employee_50,HR,Junior,149225,2021-11-10,71,1.14

# Exercise 3

In [9]:
import pandas as pd
import numpy as np

In [11]:
customers = pd.DataFrame({
    'Customer_ID': range(1000, 1020),
    'Age': np.random.randint(18, 70, 20),
    'Gender': np.random.choice(['M', 'F'], 20),
    'Income': np.random.choice(['Low', 'Medium', 'High'], 20, p=[0.4, 0.5, 0.1]),
    'Join_Date': pd.to_datetime(np.random.choice(pd.date_range('2020-01-01', '2023-01-01'), 20))
})

transactions = pd.DataFrame({
    'Transaction_ID': range(5000, 5100),
    'Customer_ID': np.random.choice(customers['Customer_ID'], 100),
    'Date': pd.to_datetime(np.random.choice(pd.date_range('2023-01-01', '2023-03-31'), 100)),
    'Amount': np.random.uniform(5, 500, 100).round(2),
    'Category': np.random.choice(['Electronics', 'Clothing', 'Groceries', 'Entertainment'], 100)
})

In [12]:
customers

    Customer_ID  Age Gender  Income  Join_Date
0          1000   65      M  Medium 2020-01-22
1          1001   24      M  Medium 2021-02-03
2          1002   35      F  Medium 2022-02-19
3          1003   64      F     Low 2020-05-16
4          1004   35      F  Medium 2021-02-09
5          1005   55      F  Medium 2020-08-26
6          1006   56      F  Medium 2021-11-26
7          1007   27      M  Medium 2022-05-24
8          1008   59      F     Low 2022-02-25
9          1009   18      M    High 2021-06-15
10         1010   69      F    High 2021-02-02
11         1011   38      F  Medium 2021-05-12
12         1012   21      M     Low 2022-06-29
13         1013   65      M    High 2022-05-13
14         1014   69      M     Low 2022-05-03
15         1015   21      M     Low 2021-12-31
16         1016   61      M    High 2020-05-24
17         1017   35      M     Low 2021-04-19
18         1018   29      F  Medium 2022-11-20
19         1019   43      M     Low 2021-10-11

In [13]:
transactions.shape

(100, 5)

Data Merging:

Merge customer data with transaction data
Find customers with no transactions (left join)
Customer Segmentation:

Group customers by age brackets (18-25, 26-35, etc.) and analyze spending
Calculate average transaction amount by income level

In [19]:
# customers with their transactions
merged=pd.merge(customers,transactions,on='Customer_ID',how="inner")
print("Merged (inner) shape:",merged.shape)

#left join
left_merged=pd.merge(customers,transactions,on="Customer_ID",how="left")
#left join keeps all customers along with customers with no transactions
no_transactions=left_merged[left_merged["Transaction_ID"].isna()]['Customer_ID'].unique()
print("Customer with no transactions:",no_transactions.tolist())

Merged (inner) shape: (100, 9)
Customer with no transactions: []

In [20]:

# Age Brackets

bins=[18,25,35,45,55,65]
labels=['18-25','26-35','36-45','46-55','56-65']
customers['Age_Bracket']=pd.cut(customers['Age'],bins=bins,labels=labels,include_lowest=True)
age_spending=pd.merge(transactions,customers[["Customer_ID","Age_Bracket"]],on="Customer_ID")
age_bracket_summary=age_spending.groupby('Age_Bracket',observed=True)['Amount'].agg(
    Total_Spending='sum',
    Avg_Transactions='mean',
    Num_Transactions='count'
).round(2)

print(age_bracket_summary)

             Total_Spending  Avg_Transactions  Num_Transactions
Age_Bracket
18-25               5986.01            230.23                26
26-35               7538.13            251.27                30
36-45               3506.65            269.74                13
46-55                672.54            224.18                 3
56-65               5674.64            283.73                20