In [1]:
import pandas as pd

In [2]:
data1 = {
    "ID" : [10001,20002,30003,40004,50005],
    "Numbers": [10,20,20,40,50],
    "Letters":["A","B","C","D","E"]
}

In [3]:
df1=pd.DataFrame(data1)
df1

      ID  Numbers Letters
0  10001       10       A
1  20002       20       B
2  30003       20       C
3  40004       40       D
4  50005       50       E

In [4]:
data2={
    "ID" : [10001,20002,30003,60006,70007],
    "Numbers" : [10,20,30,40,50],
    "City" : ['Delhi','Mumbai' ,'Agra','Nagpur','Bengalore']
}

In [5]:
df2=pd.DataFrame(data2)
df2

      ID  Numbers       City
0  10001       10      Delhi
1  20002       20     Mumbai
2  30003       30       Agra
3  60006       40     Nagpur
4  70007       50  Bengalore

In [6]:
merge_data2 = df1.merge(df2,how='inner',on='ID')
merge_data2

      ID  Numbers_x Letters  Numbers_y    City
0  10001         10       A         10   Delhi
1  20002         20       B         20  Mumbai
2  30003         20       C         30    Agra

In [ ]:
cross_merge=df1.merge(df2,how='cross')
cross_merge

     ID_x  Numbers_x Letters   ID_y  Numbers_y       City
0   10001         10       A  10001         10      Delhi
1   10001         10       A  20002         20     Mumbai
2   10001         10       A  30003         30       Agra
3   10001         10       A  60006         40     Nagpur
4   10001         10       A  70007         50  Bengalore
5   20002         20       B  10001         10      Delhi
6   20002         20       B  20002         20     Mumbai
7   20002         20       B  30003         30       Agra
8   20002         20       B  60006         40     Nagpur
9   20002         20       B  70007         50  Bengalore
10  30003         20       C  10001         10      Delhi
11  30003         20       C  20002         20     Mumbai
12  30003         20       C  30003         30       Agra
13  30003         20       C  60006         40     Nagpur
14  30003         20       C  70007         50  Bengalore
15  40004         40       D  10001         10      Delhi
16  40004         40       D  20002         20     Mumbai
17  40004         40       D  30003         30       Agra
18  40004         40       D  60006         40     Nagpur
19  40004         40       D  70007         50  Bengalore
20  50005         50       E  10001         10      Delhi
21  50005         50       E  20002         20     Mumbai
22  50005         50       E  30003         30       Agra
23  50005         50       E  60006         40     Nagpur
24  50005         50       E  70007         50  Bengalore

:

###Q1 Merge two tables given in below code(employees and departments) so you only get employees whose departments exist in the department list.
### Which employee(s) get left out? Why might that happen in a real company database?

*   Run the below code to get the two dataframes called employees and departments
*   Use these two dataframes to perform actions asked in below questions